version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
     - appnet
    volumes:
     - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
     - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
     - ./app:/var/www/html
     - ./docker/nginx/log:/var/log/nginx
     - ./docker/nginx:/start
    entrypoint: ./start/start.sh

  php:
    build: ./docker/php
    image: php
    networks:
     - appnet
    volumes:
     - ./app:/var/www/html
  cache:
    image: redis:alpine
    networks:
     - appnet
    volumes:
     - cachedata:/data
  
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: birdboard
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "33060:33060" 
    networks:
     - appnet
    volumes:
     - ./docker/mysql/dbdata:/var/lib/mysql

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
    networks:
      - appnet

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    container_name: es01
    environment:
      - "discovery.type=single-node"
      - "cluster.name=es-docker-cluster"
      - "bootstrap.memory_lock=true"
      - "ES_JAVA_OPTS=-Xms1G -Xmx1G"
      - "xpack.security.enabled=false"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    volumes:
      - ./docker/elastic/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - appnet


networks:
  appnet:
    driver: bridge
volumes:
  dbdata:
    driver: local
  cachedata:
    driver: local